#!/usr/bin/env python3
"""
Professional PDF Report Generator for Document Fraud Detection Engine v2

Usage:
    python generate_pdf_report.py forensics_report/test_invoice_tampered_fraud_report_v2.json
"""

import json
import sys
from pathlib import Path
from fpdf import FPDF


class FraudReportPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, 'Document Fraud Detection Report', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Document Fraud Detection Engine v2 | Keith Dickey - Waterville, ME', align='C')


def create_pdf_report(json_path: str, output_pdf: str = None):
    with open(json_path, 'r') as f:
        report = json.load(f)

    if output_pdf is None:
        output_pdf = str(Path(json_path).with_suffix('.pdf'))

    pdf = FraudReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Analysis of: {Path(json_path).stem}", ln=True)
    pdf.ln(3)

    # Fraud Score Box
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, f"Fraud Probability: {report['fraud_probability']}%   |   Risk: {report['risk_level']}", ln=True, fill=True)
    pdf.ln(5)

    # Recommendation
    pdf.set_font('Helvetica', '', 11)
    pdf.multi_cell(0, 6, f"Recommendation: {report['recommendation']}")
    pdf.ln(8)

    # Breakdown Table
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'Module Breakdown', ln=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(80, 8, 'Module', border=1, fill=True)
    pdf.cell(40, 8, 'Score', border=1, fill=True, align='C')
    pdf.ln()

    pdf.set_font('Helvetica', '', 10)
    for module, score in report['breakdown'].items():
        color = (255, 200, 200) if score > 50 else (200, 255, 200)
        pdf.set_fill_color(*color)
        pdf.cell(80, 8, module.replace('_', ' ').title(), border=1, fill=True)
        pdf.cell(40, 8, f"{score:.1f}", border=1, fill=True, align='C')
        pdf.ln()

    pdf.ln(8)

    # All Indicators
    if report.get('all_indicators'):
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 8, 'Key Findings', ln=True)
        pdf.set_font('Helvetica', '', 10)
        for indicator in report['all_indicators']:
            pdf.multi_cell(0, 6, f"- {indicator}")
        pdf.ln(5)

    # Footer note
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 5, "This report was generated automatically by the Document Fraud Detection Engine v2. "
                      "Copyright 2026 Keith Dickey - Waterville, Maine 04901 USA")

    pdf.output(output_pdf)
    print(f"[SUCCESS] PDF report saved to: {output_pdf}")
    return output_pdf


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_pdf_report.py <path_to_report.json>")
        sys.exit(1)
    create_pdf_report(sys.argv[1])